library(dplyr)
library(Seurat)
library(patchwork)
library(cowplot)
library(harmony)
args <- commandArgs(T)
x <- readRDS(args[1])
x <- NormalizeData(x)
x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 5000)
x <- ScaleData(x)
x <- RunPCA(x)
x <- RunHarmony(x, 'item')
x <- FindNeighbors(x, reduction = "harmony", dims = 1:50)
x <- RunUMAP(x, reduction = "harmony", dims = 1:50)
x <- FindClusters(x, resolution = 0.1)
saveRDS(x,args[2])
